#!/usr/bin/env bash

set -euo pipefail

DISABLE_SWAP=true
TOKEN_PERIOD=""

while [[ "$#" -gt 0 ]]; do
    case $1 in
        --no-swap) 
            DISABLE_SWAP=false
            shift 
            ;;
        -t|--token-period) 
            TOKEN_PERIOD="$2"
            shift 2 
            ;;
        -h|--help)
            echo "Usage: $0 [options]"
            echo "Options:"
            echo "  --no-swap                 Do not disable swap memory"
            echo "  -t, --token-period <val>  Set the token period for Terraform (default: 7d)"
            exit 0
            ;;
        *) 
            echo "Unknown parameter passed: $1"
            echo "Use --help for usage instructions."
            exit 1 
            ;;
    esac
done

echo "=== Docker ==="
DOCKER_ARGS=()
if [[ "$DISABLE_SWAP" == false ]]; then
    DOCKER_ARGS+=("--no-swap")
fi

echo "Using args:" "${DOCKER_ARGS[@]}"
./scripts/init-docker "${DOCKER_ARGS[@]}"

echo "=== Manager ==="

MANAGER_ARGS=()
if [[ -n "$TOKEN_PERIOD" ]]; then
    MANAGER_ARGS+=("-t $TOKEN_PERIOD")
fi

./scripts/init-manager "${MANAGER_ARGS[@]}"

